image: debian/stable
packages:
  - bash
  - rsync
  - podman
  - flatpak
  - elfutils
  - coreutils
  - slirp4netns
  - rootlesskit
  - binfmt-support
  - fuse-overlayfs
  - flatpak-builder
  - qemu-user-static
sources:
  - https://git.sr.ht/~elagost/signal-desktop-builder
environment:
  VERSION: "7.20.0"
secrets:
  - 07d27e19-a690-46d1-9f0a-4d391f5968b8
  - 07e0c486-ee68-4149-a12e-fa082897aefc
  - 09e35114-22ff-4920-af6a-093f59d18af3
tasks:
  - container-build: |
      cd signal-desktop-builder
      set -x
      bash ci-build.sh
      podman stop signal-desktop-$VERSION
      cp ~/signal-desktop.deb .
  - install-flatpak-deps: |
      sudo mkdir -p /opt/pakrepo
      sudo chown build /opt/pakrepo
      sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      sudo flatpak install --noninteractive --arch=x86_64 flathub org.electronjs.Electron2.BaseApp//22.08 org.freedesktop.Platform//22.08 org.freedesktop.Sdk//22.08 -y
  - build-flatpak: |
      cd signal-desktop-builder
      flatpak-builder --arch=x86_64 --gpg-sign=FBEF43DC8C6BE9A7 --repo=/opt/pakrepo --force-clean .builddir flatpak.yml
  - deploy: |
      rsync -azu --delete /opt/pakrepo/ server:/var/www/htdocs/elagost.com/flatpak/repo/
triggers:
  - action: email
    condition: always
    to: me@adamthiede.com

